import { useEffect, useState } from 'react'

const STORAGE_KEY = 'honeychain-language'

export const translations = {
  en: {
    dashboard: 'Dashboard',
    smartBeekeeping: 'Smart Beekeeping Management',
    search: 'Search',
    logout: 'Logout',
    hives: 'Hives',
    batches: 'Batches',
    verify: 'Verify',
    consumer: 'Consumer',
    labDashboard: 'Lab Dashboard',
    consumerView: 'Consumer View',
    adminPanel: 'Admin Panel',
    adminWorkspace: 'Admin Workspace',
    laboratoryWorkspace: 'Laboratory Workspace',
    beekeeperWorkspace: 'Beekeeper Workspace',
    totalHives: 'Total Hives',
    healthyHives: 'Healthy Hives',
    honeyProduced: 'Honey Produced',
    activeBatches: 'Active Batches',
    hiveWeight: 'Hive Weight (example)',
    temperature: 'Temperature',
    humidity: 'Humidity',
    alerts: 'Alerts',
    allHives: 'All Hives',
    honeyBatches: 'Honey Batches',
    trace: 'Trace',
    generateQr: 'Generate QR',
    generateAnother: 'Generate another',
    verifying: 'Checking...',
    example: 'Example',
    authenticityVerified: 'Authenticity Verified',
    batchId: 'Batch ID',
    hiveId: 'Hive ID',
    harvestDate: 'Harvest Date',
    location: 'Location',
    quantity: 'Quantity',
    scanToVerify: 'Scan to verify',
    printProof: 'Print Proof',
    openLink: 'Open Link',
    consumerLookup: 'Consumer Lookup',
    qrOrBatch: 'Enter QR token or batch ID',
    verifyProduct: 'Verify product',
    blockchainTrace: 'Blockchain Trace',
    missingBatch: 'Missing batch ID',
    stage: 'Stage',
    timestamp: 'Timestamp',
    transaction: 'Transaction',
    previous: 'Previous',
    verified: 'Verified',
    labPortal: 'Laboratory portal',
    verificationQueue: 'Verification queue',
    demoLab: 'Demo lab mode',
    submittedBatches: 'Submitted batches',
    labVerificationForm: 'Lab verification form',
    beekeeper: 'Beekeeper',
    harvest: 'Harvest',
    testType: 'Test type',
    result: 'Result',
    certificateNumber: 'Certificate number',
    testingDate: 'Testing date',
    remarks: 'Remarks',
    submitVerification: 'Submit verification',
    noBatches: 'No submitted batches found.',
    adminPanel: 'Admin Panel',
    addHive: 'Add Hive',
    add: 'Add',
    createBatch: 'Create Batch',
    create: 'Create',
    exploreDashboard: 'Explore Dashboard',
    verifyHoney: 'Verify Honey',
    howItWorks: 'How Honey Chain Works',
    smartHiveMonitoring: 'Smart Hive Monitoring',
    blockchainTraceability: 'Blockchain Traceability',
    consumerTrust: 'Consumer Trust',
    fromHiveToHome: 'From Hive to Home — Verified.',
    landingIntro: 'A smart platform combining IoT, blockchain and QR traceability to track honey from the beehive to the consumer.',
    iotStep: 'IoT sensors capture hive metrics.',
    harvestStep: 'Harvest logged as a batch and recorded on simulated blockchain.',
    qrStep: 'QR codes link consumers to the batch trace.',
    monitoringText: 'Realtime-like sensor telemetry and alerts for beekeepers.',
    traceabilityText: 'Immutable timeline for each honey batch (simulated).',
    consumerTrustText: 'Scan QR to verify origin and quality before purchase.',
    notFound: 'Not found or invalid ID',
    details: 'Details',
    traceEveryDrop: 'Trace every drop of honey from hive to home.',
    welcome: 'Welcome',
    signInContinue: 'Sign in to continue',
    username: 'Username',
    password: 'Password',
    loginDashboard: 'Login to dashboard',
    quickDemo: 'Quick demo access',
    hiveMonitoring: 'Hive monitoring',
    fasterTraceability: 'Faster traceability',
    batchVisibility: 'Batch visibility',
    liveHarvest: 'Live harvest',
    whyTeams: 'Why teams choose Honey Chain',
    trustEveryStep: 'Everything you need to build trust at every step',
    loading: 'Loading...',
    lastUpdated: 'Last updated',
    hiveAlert: 'Hive HIVE-002 high temperature',
    monitorBees: 'Monitor beehives, verify harvest batches, and provide secure product traceability through a connected smart beekeeping dashboard.',
    adminOrUser: 'admin or user',
    enterPassword: 'Enter password',
    liveHiveInsights: 'Live Hive Insights',
    liveHiveText: 'Track temperature, humidity, and weight in one operational dashboard.',
    blockchainProof: 'Blockchain Proof',
    blockchainProofText: 'Create immutable traceability records for every harvest and supply chain checkpoint.',
    consumerConfidence: 'Consumer Confidence',
    consumerConfidenceText: 'Link each batch to a QR code and verify origin instantly before every purchase.',
    verified: 'Verified',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    smartBeekeeping: 'स्मार्ट मधुमक्खी पालन प्रबंधन',
    search: 'खोजें',
    logout: 'लॉग आउट',
    hives: 'छत्ते',
    batches: 'बैच',
    verify: 'सत्यापित करें',
    consumer: 'उपभोक्ता',
    labDashboard: 'लैब डैशबोर्ड',
    consumerView: 'उपभोक्ता दृश्य',
    adminPanel: 'एडमिन पैनल',
    adminWorkspace: 'एडमिन कार्यक्षेत्र',
    laboratoryWorkspace: 'प्रयोगशाला कार्यक्षेत्र',
    beekeeperWorkspace: 'मधुमक्खी पालक कार्यक्षेत्र',
    totalHives: 'कुल छत्ते',
    healthyHives: 'स्वस्थ छत्ते',
    honeyProduced: 'उत्पादित शहद',
    activeBatches: 'सक्रिय बैच',
    hiveWeight: 'छत्ते का वजन (उदाहरण)',
    temperature: 'तापमान',
    humidity: 'नमी',
    alerts: 'अलर्ट',
    allHives: 'सभी छत्ते',
    honeyBatches: 'शहद के बैच',
    trace: 'ट्रेस देखें',
    generateQr: 'QR बनाएं',
    generateAnother: 'एक और बनाएं',
    verifying: 'जांच हो रही है...',
    example: 'उदाहरण',
    authenticityVerified: 'प्रामाणिकता सत्यापित',
    batchId: 'बैच आईडी',
    hiveId: 'छत्ता आईडी',
    harvestDate: 'कटाई की तारीख',
    location: 'स्थान',
    quantity: 'मात्रा',
    scanToVerify: 'सत्यापन के लिए स्कैन करें',
    printProof: 'प्रमाण प्रिंट करें',
    openLink: 'लिंक खोलें',
    consumerLookup: 'उपभोक्ता खोज',
    qrOrBatch: 'QR टोकन या बैच आईडी दर्ज करें',
    verifyProduct: 'उत्पाद सत्यापित करें',
    blockchainTrace: 'ब्लॉकचेन ट्रेस',
    missingBatch: 'बैच आईडी उपलब्ध नहीं है',
    stage: 'चरण',
    timestamp: 'समय',
    transaction: 'लेन-देन',
    previous: 'पिछला',
    verified: 'सत्यापित',
    labPortal: 'प्रयोगशाला पोर्टल',
    verificationQueue: 'सत्यापन कतार',
    demoLab: 'डेमो लैब मोड',
    submittedBatches: 'जमा किए गए बैच',
    labVerificationForm: 'लैब सत्यापन फॉर्म',
    beekeeper: 'मधुमक्खी पालक',
    harvest: 'कटाई',
    testType: 'परीक्षण प्रकार',
    result: 'परिणाम',
    certificateNumber: 'प्रमाणपत्र संख्या',
    testingDate: 'परीक्षण की तारीख',
    remarks: 'टिप्पणियां',
    submitVerification: 'सत्यापन जमा करें',
    noBatches: 'कोई जमा बैच नहीं मिला।',
    addHive: 'छत्ता जोड़ें',
    add: 'जोड़ें',
    createBatch: 'बैच बनाएं',
    create: 'बनाएं',
    exploreDashboard: 'डैशबोर्ड देखें',
    verifyHoney: 'शहद सत्यापित करें',
    howItWorks: 'Honey Chain कैसे काम करता है',
    smartHiveMonitoring: 'स्मार्ट छत्ता निगरानी',
    blockchainTraceability: 'ब्लॉकचेन ट्रेसबिलिटी',
    consumerTrust: 'उपभोक्ता विश्वास',
    fromHiveToHome: 'छत्ते से घर तक — सत्यापित।',
    landingIntro: 'IoT, ब्लॉकचेन और QR ट्रेसबिलिटी से बना स्मार्ट प्लेटफॉर्म, जो छत्ते से उपभोक्ता तक शहद को ट्रैक करता है।',
    iotStep: 'IoT सेंसर छत्ते के आंकड़े एकत्र करते हैं।',
    harvestStep: 'कटाई को बैच के रूप में दर्ज कर सिम्युलेटेड ब्लॉकचेन पर रिकॉर्ड किया जाता है।',
    qrStep: 'QR कोड उपभोक्ताओं को बैच ट्रेस से जोड़ते हैं।',
    monitoringText: 'मधुमक्खी पालकों के लिए सेंसर टेलीमेट्री और अलर्ट।',
    traceabilityText: 'हर शहद बैच की अपरिवर्तनीय समयरेखा (सिम्युलेटेड)।',
    consumerTrustText: 'खरीद से पहले उत्पत्ति और गुणवत्ता सत्यापित करने के लिए QR स्कैन करें।',
    notFound: 'आईडी नहीं मिली या अमान्य है',
    details: 'विवरण',
    traceEveryDrop: 'छत्ते से घर तक शहद की हर बूंद को ट्रैक करें।',
    welcome: 'स्वागत है',
    signInContinue: 'जारी रखने के लिए साइन इन करें',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    loginDashboard: 'डैशबोर्ड में लॉग इन करें',
    quickDemo: 'त्वरित डेमो एक्सेस',
    hiveMonitoring: 'छत्ता निगरानी',
    fasterTraceability: 'तेज ट्रेसबिलिटी',
    batchVisibility: 'बैच दृश्यता',
    liveHarvest: 'लाइव कटाई',
    whyTeams: 'टीमें Honey Chain क्यों चुनती हैं',
    trustEveryStep: 'हर चरण में विश्वास बनाने के लिए जरूरी सुविधाएं',
    loading: 'लोड हो रहा है...',
    lastUpdated: 'अंतिम अपडेट',
    hiveAlert: 'छत्ते HIVE-002 का तापमान अधिक है',
    monitorBees: 'कनेक्टेड स्मार्ट मधुमक्खी पालन डैशबोर्ड से छत्तों की निगरानी करें, कटाई बैच सत्यापित करें और सुरक्षित ट्रेसबिलिटी दें।',
    adminOrUser: 'एडमिन या उपयोगकर्ता',
    enterPassword: 'पासवर्ड दर्ज करें',
    liveHiveInsights: 'लाइव छत्ता जानकारी',
    liveHiveText: 'एक ही ऑपरेशनल डैशबोर्ड में तापमान, नमी और वजन ट्रैक करें।',
    blockchainProof: 'ब्लॉकचेन प्रमाण',
    blockchainProofText: 'हर कटाई और सप्लाई चेन चरण के लिए अपरिवर्तनीय ट्रेसबिलिटी रिकॉर्ड बनाएं।',
    consumerConfidence: 'उपभोक्ता भरोसा',
    consumerConfidenceText: 'हर बैच को QR कोड से जोड़ें और तुरंत उत्पत्ति सत्यापित करें।',
    verified: 'सत्यापित',
  },
}

export function getLanguage() {
  return localStorage.getItem(STORAGE_KEY) === 'hi' ? 'hi' : 'en'
}

export function setLanguage(language) {
  const next = language === 'hi' ? 'hi' : 'en'
  localStorage.setItem(STORAGE_KEY, next)
  window.dispatchEvent(new CustomEvent('honeychain-language-change', { detail: next }))
}

export function useLanguage() {
  const [language, setCurrentLanguage] = useState(getLanguage)

  useEffect(() => {
    const handleChange = (event) => setCurrentLanguage(event.detail || getLanguage())
    window.addEventListener('honeychain-language-change', handleChange)
    return () => window.removeEventListener('honeychain-language-change', handleChange)
  }, [])

  const toggleLanguage = () => setLanguage(language === 'en' ? 'hi' : 'en')
  return { language, toggleLanguage, t: translations[language] }
}
