services:
  - type: web
    name: honey-chain
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      npm install
      cd server && npm install && cd ..
      cd client && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
